model:
  name: lgbm
  batch_size: 4096
  n_jobs: 24

lgbm:
  loss: huber
  learning_rate: 0.10
  num_boost_round: 400
  early_stop: 20
  early_stopping_min_delta: 0.0
  log_evaluation_period: 50
  colsample_bytree: 0.85
  subsample: 0.85
  subsample_freq: 1
  lambda_l1: 1.0
  lambda_l2: 1.0
  max_depth: 6
  num_leaves: 31
  min_data_in_leaf: 150
  num_threads: 24
  seed: 42
