alpha_version: 158

native:
  universe_dir: ./data/universes

artifacts:
  enable_local_store: true
  store_dir: ./results/experiments

universe: csi300

time:
  train: ["2016-01-01", "2020-12-31"]
  valid: ["2021-01-01", "2021-12-31"]
  test:  ["2022-01-01", "2025-12-31"]

features:
  profile: core_v1
  transforms:
    cross_sectional_rank: true
  handler: Alpha158
  lookback: 20
  use_valuation: True

model:
  preset: lgbm_default

strategy:
  topk: 30
  n_drop: 5

backtest:
  cost:
    buy: 0.001
    sell: 0.001
  slippage: 0.0
  min_cost: 5
  account: 100000000
  risk_degree: 0.95
