native:
  universe_dir: ./data/universes

artifacts:
  enable_local_store: true
  store_dir: ./results/experiments

universe: csi300_real

time:
  train: ["2016-01-01", "2022-12-31"]
  valid: ["2023-01-01", "2023-12-31"]
  test:  ["2024-01-01", "2025-12-31"]

features:
  alpha: 158
  profile: alpha158_full
  # selected_columns:
  #   - KMID
  #   - MA20
  #   - RSV20
  handler: Alpha158
  lookback: 20
  use_valuation: True

model:
  preset: lgbm_default

strategy:
  topk: 30
  n_drop: 5

backtest:
  cost:
    buy: 0.0003
    sell: 0.0013
  slippage: 0.0005
  min_cost: 5
  account: 100000000
  risk_degree: 0.95
