"""Native backtest aligned with Qlib TopkDropoutStrategy semantics."""

from src.backtest_engine import (
    DEFAULT_ACCOUNT,
    DEFAULT_MIN_COST,
    DEFAULT_RISK_DEGREE,
    DEFAULT_SLIPPAGE,
    DEFAULT_TRANSACTION_COST,
    run_native_backtest,
    run_native_backtest_batch,
)
from src.backtest_scoring import (
    DEFAULT_SCORE_TRANSFORM,
    DEFAULT_WEIGHTING,
    SUPPORTED_SCORE_TRANSFORMS,
    SUPPORTED_WEIGHTING_MODES,
)
from src.backtest_controls import (
    INTRAPERIOD_PRICE_CONFIRM_EXECUTION_TIMING,
    INTRAPERIOD_PRICE_CONFIRM_SIGNAL_TIMING,
    SUPPORTED_EXIT_SCORE_SOURCES,
    SUPPORTED_INTRAPERIOD_EXIT_CALIBRATIONS,
    SUPPORTED_INTRAPERIOD_EXIT_MODES,
    SUPPORTED_INTRAPERIOD_PRICE_CONFIRM_MODES,
    SUPPORTED_RISK_CONTROL_MODES,
    SUPPORTED_SIGNAL_STRENGTH_METRICS,
)

__all__ = [
    "DEFAULT_ACCOUNT",
    "DEFAULT_MIN_COST",
    "DEFAULT_RISK_DEGREE",
    "DEFAULT_SLIPPAGE",
    "DEFAULT_TRANSACTION_COST",
    "DEFAULT_WEIGHTING",
    "SUPPORTED_WEIGHTING_MODES",
    "DEFAULT_SCORE_TRANSFORM",
    "SUPPORTED_SCORE_TRANSFORMS",
    "SUPPORTED_RISK_CONTROL_MODES",
    "SUPPORTED_SIGNAL_STRENGTH_METRICS",
    "SUPPORTED_INTRAPERIOD_EXIT_MODES",
    "SUPPORTED_EXIT_SCORE_SOURCES",
    "SUPPORTED_INTRAPERIOD_EXIT_CALIBRATIONS",
    "SUPPORTED_INTRAPERIOD_PRICE_CONFIRM_MODES",
    "INTRAPERIOD_PRICE_CONFIRM_SIGNAL_TIMING",
    "INTRAPERIOD_PRICE_CONFIRM_EXECUTION_TIMING",
    "run_native_backtest",
    "run_native_backtest_batch",
]
